kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: eproject-cluster
nodes:
  # Control plane node
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    # API Gateway
    - containerPort: 30003
      hostPort: 3003
      protocol: TCP
    # Auth Service
    - containerPort: 30000
      hostPort: 3000
      protocol: TCP
    # Product Service
    - containerPort: 30001
      hostPort: 3001
      protocol: TCP
    # Order Service
    - containerPort: 30002
      hostPort: 3002
      protocol: TCP
    # MongoDB
    - containerPort: 30017
      hostPort: 27017
      protocol: TCP
    # RabbitMQ
    - containerPort: 30672
      hostPort: 5672
      protocol: TCP
    - containerPort: 31672
      hostPort: 15672
      protocol: TCP
  
  # Worker node
  - role: worker
