apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "your_jwt_secret_key_here"
  mongodb-auth-uri: "mongodb://mongodb:27017/auth"
  mongodb-product-uri: "mongodb://mongodb:27017/product"
  mongodb-order-uri: "mongodb://mongodb:27017/order"
  rabbitmq-uri: "amqp://admin:admin@rabbitmq:5672"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Auth Service
  AUTH_PORT: "3000"
  
  # Product Service
  PRODUCT_PORT: "3001"
  RABBITMQ_QUEUE_PRODUCT: "products"
  RABBITMQ_QUEUE_ORDER: "orders"
  ORDER_SERVICE_URL: "http://order-service:3002"
  
  # Order Service
  ORDER_PORT: "3002"
  
  # API Gateway
  GATEWAY_PORT: "3003"
  AUTH_SERVICE_URL: "http://auth-service:3000"
  PRODUCT_SERVICE_URL: "http://product-service:3001"
  ORDER_SERVICE_URL: "http://order-service:3002"
